/*
 * Globalize Culture es-NI
 *
 * http://github.com/jquery/globalize
 *
 * Copyright Software Freedom Conservancy, Inc.
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * This file was generated by the Globalize Culture Generator
 * Translation: bugs found in this file need to be fixed in the generator
 */

(function( window, undefined ) {

var Globalize;

if ( typeof require !== "undefined" &&
	typeof exports !== "undefined" &&
	typeof module !== "undefined" ) {
	// Assume CommonJS
	Globalize = require( "globalize" );
} else {
	// Global variable
	Globalize = window.Globalize;
}

Globalize.addCultureInfo( "es-NI", "default", {
	name: "es-NI",
	englishName: "Spanish (Nicaragua)",
	nativeName: "Español (Nicaragua)",
	language: "es",
	numberFormat: {
		"NaN": "NeuN",
		negativeInfinity: "-Infinito",
		positiveInfinity: "Infinito",
		currency: {
			pattern: ["($ n)","$ n"],
			groupSizes: [3,0],
			symbol: "C$"
		}
	},
	calendars: {
		standard: {
			days: {
				names: ["domingo","lunes","martes","miércoles","jueves","viernes","sábado"],
				namesAbbr: ["dom","lun","mar","mié","jue","vie","sáb"],
				namesShort: ["do","lu","ma","mi","ju","vi","sá"]
			},
			months: {
				names: ["enero","febrero","marzo","abril","mayo","junio","julio","agosto","septiembre","octubre","noviembre","diciembre",""],
				namesAbbr: ["ene","feb","mar","abr","may","jun","jul","ago","sep","oct","nov","dic",""]
			},
			AM: ["a.m.","a.m.","A.M."],
			PM: ["p.m.","p.m.","P.M."],
			eras: [{"name":"d.C.","start":null,"offset":0}],
			patterns: {
				d: "dd/MM/yyyy",
				D: "dddd, dd' de 'MMMM' de 'yyyy",
				t: "hh:mm tt",
				T: "hh:mm:ss tt",
				f: "dddd, dd' de 'MMMM' de 'yyyy hh:mm tt",
				F: "dddd, dd' de 'MMMM' de 'yyyy hh:mm:ss tt",
				M: "dd MMMM",
				Y: "MMMM' de 'yyyy"
			}
		}
	}
});

}( this ));


var localizationobj = {};
localizationobj.percentsymbol = "%";
localizationobj.currencysymbol = "$";
localizationobj.currencysymbolposition = "anterior";
localizationobj.decimalseparator = ".";
localizationobj.thousandsseparator = ",";
localizationobj.pagergotopagestring = "Ir a página=";
localizationobj.pagershowrowsstring = "Mostrar filas=";
localizationobj.pagerrangestring = " de ";
localizationobj.pagerpreviousbuttonstring = "previo";
localizationobj.pagernextbuttonstring = "siguiente";
localizationobj.groupsheaderstring = "Arrastre una columna para que se agrupe por ella";
localizationobj.sortascendingstring = "Ordenar Acs";
localizationobj.sortdescendingstring = "Ordenar Des";
localizationobj.sortremovestring = "Quitar orden";
localizationobj.groupbystring = "Agrupar por esta columna";
localizationobj.groupremovestring = "Quitar de grupos";
localizationobj.filterclearstring = "Limpiar";
localizationobj.filterstring = "Filtro";
localizationobj.filtershowrowstring = "Mostrar filas donde=";
localizationobj.filtershowrowdatestring = "Mostrar filas donde fecha=";
localizationobj.filterorconditionstring = "O";
localizationobj.filterandconditionstring = "Y";
localizationobj.filterselectallstring = "(Seleccionar Todo)";
localizationobj.filterchoosestring = "Por favor seleccione:";
localizationobj.filterstringcomparisonoperators = ['vacio', 'no vacio', 'contenga', 'contenga(coicidir Mayusculas/Minusculas)',
'no contenga', 'no contenga(coincidir Mayusculas/Minusculas)', 'inicia con', 'inicia con(coicidir Mayusculas/Minusculas)',
'termina con', 'termina con(coicidir Mayusculas/Minusculas)', 'igual', 'igual(coicidir Mayusculas/Minusculas)', 'null', 'no null'];
localizationobj.filternumericcomparisonoperators = ['=', '!=', '<', '<=', '>', '>=', 'null', 'no null'];
localizationobj.filterdatecomparisonoperators = ['=', '!=', '<', '<=', '>', '>=', 'null', 'no null'];
localizationobj.filterbooleancomparisonoperators = ['=', '!='];
localizationobj.validationstring = "Valor no valido";
localizationobj.emptydatastring = "No hay registros que mostrar";
localizationobj.filterselectstring = "Seleccione un Filtro";
localizationobj.loadtext = "Cargando…";
localizationobj.clearstring = "Limpiar";
localizationobj.todaystring = "hoy";
